name: Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service-name: "user-service"

  deploy:
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Deployment
        run: echo "🚀 Deploying user-service to production..."
