name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: cd ${{ inputs.service-name }} && npm install

      - name: Run Tests
        run: cd ${{ inputs.service-name }} && npm test
